(SELECT U.NAME AS RESULTS
FROM MOVIERATING R
JOIN USERS U ON U.USER_ID = R.USER_ID
GROUP BY R.USER_ID
ORDER BY COUNT(*) DESC, U.NAME ASC
LIMIT 1)

UNION ALL

(SELECT M.TITLE AS RESULTS
FROM MOVIERATING R
JOIN MOVIES M ON M.MOVIE_ID = R.MOVIE_ID
WHERE R.CREATED_AT BETWEEN '2020-02-01' AND '2020-02-29'
GROUP BY M.MOVIE_ID
ORDER BY AVG(R.RATING) DESC, M.TITLE ASC
LIMIT 1)